//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinconArtesano.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.File = new HashSet<File>();
            this.FilePath = new HashSet<FilePath>();
        }
    
        public int ProductId { get; set; }
        public int UsersId { get; set; }
        public string ProductTitle { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> IdCategory { get; set; }
        public Nullable<System.DateTime> DateNull { get; set; }
        public System.DateTime DeteAdd { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilePath> FilePath { get; set; }
    }
}
