//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinconArtesano.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoVigentesProducts
    {
        public int ProductId { get; set; }
        public string UsersId { get; set; }
        public string ProductTitle { get; set; }
        public string ProductDescription { get; set; }
        public int IdCategory { get; set; }
        public Nullable<System.DateTime> DateNull { get; set; }
        public System.DateTime DateAdd { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
        public bool IsBlocked { get; set; }
    }
}
