//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Messages()
        {
            this.Messages1 = new HashSet<Messages>();
        }
    
        public int IdComentario { get; set; }
        public Nullable<int> IdComentarioPadre { get; set; }
        public string UsersId { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Message { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
        public System.DateTime DateAdd { get; set; }
        public Nullable<System.DateTime> DateNull { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Messages> Messages1 { get; set; }
        public virtual Messages Messages2 { get; set; }
    }
}
